# Generated by Django 4.1 on 2022-08-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photovoltaic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="pvdata", name="created_at",),
        migrations.RemoveField(model_name="pvdata", name="updated_at",),
    ]
