# Generated by Django 4.1 on 2022-08-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photovoltaic", "0002_remove_pvdata_created_at_remove_pvdata_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pvdata",
            name="current_s1",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pvdata",
            name="current_s2",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pvdata",
            name="irradiation",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pvdata",
            name="power_avg",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pvdata",
            name="power_s1",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pvdata",
            name="power_s2",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pvdata",
            name="temperature_amb",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pvdata",
            name="temperature_pv",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pvdata",
            name="voltage_s1",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pvdata",
            name="voltage_s2",
            field=models.FloatField(default=0, null=True),
        ),
    ]
