# Generated by Django 4.1 on 2022-08-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "photovoltaic",
            "0003_alter_pvdata_current_s1_alter_pvdata_current_s2_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PVString",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=1024, primary_key=True, serialize=False
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("voltage", models.FloatField(default=0, null=True)),
                ("current", models.FloatField(default=0, null=True)),
                ("power", models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(model_name="pvdata", name="current_s1",),
        migrations.RemoveField(model_name="pvdata", name="current_s2",),
        migrations.RemoveField(model_name="pvdata", name="power_s1",),
        migrations.RemoveField(model_name="pvdata", name="power_s2",),
        migrations.RemoveField(model_name="pvdata", name="voltage_s1",),
        migrations.RemoveField(model_name="pvdata", name="voltage_s2",),
        migrations.AddField(
            model_name="pvdata",
            name="strings",
            field=models.ManyToManyField(to="photovoltaic.pvstring"),
        ),
    ]
