# Generated by Django 4.1 on 2022-08-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photovoltaic", "0005_powerforecast"),
    ]

    operations = [
        migrations.CreateModel(
            name="YieldDay",
            fields=[
                ("timestamp", models.DateTimeField(primary_key=True, serialize=False)),
                ("yield_day", models.FloatField(default=0, null=True)),
                ("yield_day_forecast", models.FloatField(default=0, null=True)),
            ],
        ),
    ]
