# Generated by Django 3.2 on 2022-08-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photovoltaic', '0006_yieldday'),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldMonth',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('yield_month', models.FloatField(default=0, null=True)),
                ('yield_month_forecast', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
