# Generated by Django 3.2 on 2022-08-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photovoltaic', '0007_yieldmonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldYear',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('yield_year', models.FloatField(default=0, null=True)),
                ('yield_year_forecast', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
