# Generated by Django 3.2 on 2022-08-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photovoltaic', '0009_auto_20220825_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTreshold',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('VT', 'Voltage'), ('CR', 'Current')], default='VT', max_length=2)),
                ('meteorological_value', models.FloatField(default=0)),
                ('treshold_max', models.FloatField(default=0)),
                ('treshold_min', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='YieldMinute',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('yield_minute', models.FloatField(default=0, null=True)),
                ('yield_day_forecast', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
