# Generated by Django 3.2 on 2022-08-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photovoltaic', '0011_pvstring_string_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerttreshold',
            old_name='treshold_max',
            new_name='treshold_ft_max',
        ),
        migrations.RenameField(
            model_name='alerttreshold',
            old_name='treshold_min',
            new_name='treshold_ft_min',
        ),
        migrations.AddField(
            model_name='alerttreshold',
            name='string_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alerttreshold',
            name='treshold_wa_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='alerttreshold',
            name='treshold_wa_min',
            field=models.FloatField(default=0),
        ),
    ]
