# Generated by Django 3.2 on 2022-08-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photovoltaic', '0012_auto_20220826_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fault_vt_percentile', models.IntegerField(default=98)),
                ('warning_vt_percentile', models.IntegerField(default=88)),
                ('delt_vt', models.FloatField(default=0.6)),
                ('fault_cr_percentile', models.IntegerField(default=98)),
                ('warning_cr_percentile', models.IntegerField(default=88)),
                ('delt_cr', models.FloatField(default=5)),
                ('fault_user_active', models.BooleanField(default=True)),
                ('warning_user_active', models.BooleanField(default=True)),
                ('alert_days_active', models.BooleanField(default=False)),
                ('retraining_interval', models.IntegerField(default=3)),
            ],
        ),
    ]
